substitutions:
  device_name: nexxtender
  friendly_name: Nexxtender
  update_interval: 30s
  nexxtender_mac: !secret nexxtender_mac
  nexxtender_pin: !secret nexxtender_passkey

esp32:
  board: esp32dev #Replace according to the esp32 you're using
  framework:
    type: esp-idf
    version: recommended

packages:
  MyNexxtender: github://bananias/MyNexxtender/package/nexxtender.yaml

esphome:
  name: ${device_name}
  friendly_name: ${friendly_name}
  name_add_mac_suffix: false

api:
  encryption:
    key: !secret esphome_api_key

ota:

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    ssid: ${device_name}-AP
    password: !secret esphome_admin_password

logger:

captive_portal:
